### ISSUE TITLE
Documentation with read the docs

### ISSUE THREAD

**Issue by oloapinivad** [oloapinivad/ECmean4#30]
In branch `documentation` (and in `documentation-api`) we implemented a initial version of sphinx+readthedocs to provide an automatic documentation procedure.
The default documentation works fine, and can be fine https://ecmean4.readthedocs.io/en/latest/

However, the autodoc part, which builds the description of the functions starting from the function descriptions, appears to be a pain. Indeed, it works smoothly locally using sphinx in two different configuration, which involve the use of the sphinx-api  (7376c0157b24c48327024007583f8cb5a09ff248) or of the autosummary (cae29f2d58789f5e65a31161a16218856d83216d). 

From a "style" point of view, the sphinx-api solution seems better, so that this is considered the preferred one so far and it is installed on the webpage. 

When we move on the server using readthedocs, both fails since they appear to not be able to find the correct modules. I suspect this is associated with the interdependnecies of the two scripts, which probably should be two different modules, but still it puzzles me a lot that both crashes. 

An example of the crash for the sphinx-api solution: actually these are just errors. 
```
WARNING: autodoc: failed to import module 'global_mean'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ecmean4/envs/latest/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 62, in import_module
    return importlib.import_module(modname)
  File "/home/docs/.asdf/installs/python/3.9.7/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/ecmean4/checkouts/latest/global_mean.py", line 23, in <module>
    from ecmean import var_is_there, load_yaml, \
  File "/home/docs/checkouts/readthedocs.org/user_builds/ecmean4/checkouts/latest/ecmean.py", line 17, in <module>
    cdo = Cdo()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ecmean4/envs/latest/lib/python3.9/site-packages/cdo.py", line 187, in __init__
    self.operators         = self.__getOperators()
  File "/home/docs/checkouts/readthedocs.org/user_builds/ecmean4/envs/latest/lib/python3.9/site-packages/cdo.py", line 278, in __getOperators
    version = parse_version(getCdoVersion(self.CDO))
  File "/home/docs/checkouts/readthedocs.org/user_builds/ecmean4/envs/latest/lib/python3.9/site-packages/cdo.py", line 78, in getCdoVersion
    proc = subprocess.Popen([path2cdo, '-V'], stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/home/docs/.asdf/installs/python/3.9.7/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/docs/.asdf/installs/python/3.9.7/lib/python3.9/subprocess.py", line 1696, in _execute_child
    and os.path.dirname(executable)
  File "/home/docs/.asdf/installs/python/3.9.7/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
```
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by oloapinivad** [comment]
So after a bit of digging this was due to cdo that has to be installed on the virtual machine. Once this is done, it built smoothly.
